CREATE TABLE bronze.census_g01_nsw_lga_bronze (
    LGA_CODE_2016 VARCHAR(255),
    Tot_P_M INTEGER,
    Tot_P_F INTEGER,
    Tot_P_P INTEGER,
    Age_0_4_yr_M INTEGER,
    Age_0_4_yr_F INTEGER,
    Age_0_4_yr_P INTEGER,
    Age_5_14_yr_M INTEGER,
    Age_5_14_yr_F INTEGER,
    Age_5_14_yr_P INTEGER,
    Age_15_19_yr_M INTEGER,
    Age_15_19_yr_F INTEGER,
    Age_15_19_yr_P INTEGER,
    Age_20_24_yr_M INTEGER,
    Age_20_24_yr_F INTEGER,
    Age_20_24_yr_P INTEGER,
    Age_25_34_yr_M INTEGER,
    Age_25_34_yr_F INTEGER,
    Age_25_34_yr_P INTEGER,
    Age_35_44_yr_M INTEGER,
    Age_35_44_yr_F INTEGER,
    Age_35_44_yr_P INTEGER,
    Age_45_54_yr_M INTEGER,
    Age_45_54_yr_F INTEGER,
    Age_45_54_yr_P INTEGER,
    Age_55_64_yr_M INTEGER,
    Age_55_64_yr_F INTEGER,
    Age_55_64_yr_P INTEGER,
    Age_65_74_yr_M INTEGER,
    Age_65_74_yr_F INTEGER,
    Age_65_74_yr_P INTEGER,
    Age_75_84_yr_M INTEGER,
    Age_75_84_yr_F INTEGER,
    Age_75_84_yr_P INTEGER,
    Age_85ov_M INTEGER,
    Age_85ov_F INTEGER,
    Age_85ov_P INTEGER,
    Median_age_P INTEGER,
    Average_household_size FLOAT,
    Median_P_weekly_rent INTEGER,
    Median_P_mortgage_repay_monthly INTEGER
);

CREATE TABLE bronze.census_g02_nsw_lga_bronze (
    LGA_CODE_2016 VARCHAR(255),
    Median_age_persons INTEGER,
    Median_mortgage_repay_monthly INTEGER,
    Median_tot_prsnl_inc_weekly INTEGER,
    Median_rent_weekly INTEGER,
    Median_tot_fam_inc_weekly INTEGER,
    Average_num_psns_per_bedroom FLOAT,
    Median_tot_hhd_inc_weekly INTEGER,
    Average_household_size FLOAT
);