CREATE TABLE IF NOT EXISTS bronze.census_lga_bronze (
        LGA_CODE_2016 TEXT PRIMARY KEY,
        Tot_P_M INTEGER,
        Tot_P_F INTEGER,
        Tot_P_P INTEGER,
        Age_0_4_yr_M INTEGER,
        Age_0_4_yr_F INTEGER,
        Age_0_4_yr_P INTEGER,
        Age_5_14_yr_M INTEGER,
        Age_5_14_yr_F INTEGER,
        Age_5_14_yr_P INTEGER,
        Age_15_19_yr_M INTEGER,
        Age_15_19_yr_F INTEGER,
        Age_15_19_yr_P INTEGER,
        Age_20_24_yr_M INTEGER,
        Age_20_24_yr_F INTEGER,
        Age_20_24_yr_P INTEGER,
        Age_25_34_yr_M INTEGER,
        Age_25_34_yr_F INTEGER,
        Age_25_34_yr_P INTEGER,
        Age_35_44_yr_M INTEGER,
        Age_35_44_yr_F INTEGER,
        Age_35_44_yr_P INTEGER,
        Age_45_54_yr_M INTEGER,
        Age_45_54_yr_F INTEGER,
        Age_45_54_yr_P INTEGER,
        Age_55_64_yr_M INTEGER,
        Age_55_64_yr_F INTEGER,
        Age_55_64_yr_P INTEGER,
        Age_65_74_yr_M INTEGER,
        Age_65_74_yr_F INTEGER,
        Age_65_74_yr_P INTEGER,
        Age_75_84_yr_M INTEGER,
        Age_75_84_yr_F INTEGER,
        Age_75_84_yr_P INTEGER,
        Age_85ov_M INTEGER,
        Age_85ov_F INTEGER,
        Age_85ov_P INTEGER,
        Median_age_persons INTEGER,
        Average_household_size NUMERIC,
        Median_Tot_P_incom INTEGER,
        Median_Tot_HHD_incom INTEGER,
        Median_Tot_FAM_incom INTEGER,
        load_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);